### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jhgr16** [JohnyMac/ExtremeStudio#14]
1.- When i select a function from the object explorer or i scroll, some times this window appear and i need restart extremestudio. (I think its the scrollbar)
```
See the end of this message for details on invoking  
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at ScintillaWrapper.<.ctor>b__1_0(Object sender, UpdateUIEventArgs args)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at ScintillaNET.Scintilla.OnUpdateUI(UpdateUIEventArgs e)
   at ScintillaNET.Scintilla.WmReflectNotify(Message& m)
   at ScintillaNET.Scintilla.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
ExtremeStudio
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Gonz%C3%A1lez/AppData/Local/Apps/2.0/LA666H2J.Y66/703WBKCZ.57Q/extr..tion_0000000000000000_0001.0000_5df0a81931a00ba2/ExtremeStudio.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
ExtremeCore
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Gonz%C3%A1lez/AppData/Local/Apps/2.0/LA666H2J.Y66/703WBKCZ.57Q/extr..tion_0000000000000000_0001.0000_5df0a81931a00ba2/ExtremeCore.DLL
----------------------------------------
System.Windows.Forms.Ribbon35
    Assembly Version: 3.5.8.0
    Win32 Version: 3.5.8.0
    CodeBase: file:///C:/Users/Gonz%C3%A1lez/AppData/Local/Apps/2.0/LA666H2J.Y66/703WBKCZ.57Q/extr..tion_0000000000000000_0001.0000_5df0a81931a00ba2/System.Windows.Forms.Ribbon35.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.3.19514
    CodeBase: file:///C:/Users/Gonz%C3%A1lez/AppData/Local/Apps/2.0/LA666H2J.Y66/703WBKCZ.57Q/extr..tion_0000000000000000_0001.0000_5df0a81931a00ba2/Newtonsoft.Json.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 2.9.0.0
    Win32 Version: 2.9.0.0
    CodeBase: file:///C:/Users/Gonz%C3%A1lez/AppData/Local/Apps/2.0/LA666H2J.Y66/703WBKCZ.57Q/extr..tion_0000000000000000_0001.0000_5df0a81931a00ba2/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
Ionic.Zip
    Assembly Version: 1.9.9.0
    Win32 Version: 1.9.9
    CodeBase: file:///C:/Users/Gonz%C3%A1lez/AppData/Local/Apps/2.0/LA666H2J.Y66/703WBKCZ.57Q/extr..tion_0000000000000000_0001.0000_5df0a81931a00ba2/Ionic.Zip.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.101.0
    Win32 Version: 1.0.101.0
    CodeBase: file:///C:/Users/Gonz%C3%A1lez/AppData/Local/Apps/2.0/LA666H2J.Y66/703WBKCZ.57Q/extr..tion_0000000000000000_0001.0000_5df0a81931a00ba2/System.Data.SQLite.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
ScintillaNET
    Assembly Version: 3.5.6.0
    Win32 Version: 3.5.6.0
    CodeBase: file:///C:/Users/Gonz%C3%A1lez/AppData/Local/Apps/2.0/LA666H2J.Y66/703WBKCZ.57Q/extr..tion_0000000000000000_0001.0000_5df0a81931a00ba2/ScintillaNET.DLL
----------------------------------------
AutocompleteMenu-ScintillaNET
    Assembly Version: 1.3.4.0
    Win32 Version: 1.3.4.0
    CodeBase: file:///C:/Users/Gonz%C3%A1lez/AppData/Local/Apps/2.0/LA666H2J.Y66/703WBKCZ.57Q/extr..tion_0000000000000000_0001.0000_5df0a81931a00ba2/AutocompleteMenu-ScintillaNET.DLL
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
ThemeVS2012Light
    Assembly Version: 2.9.0.0
    Win32 Version: 2.9.0.0
    CodeBase: file:///C:/Users/Gonz%C3%A1lez/AppData/Local/Apps/2.0/LA666H2J.Y66/703WBKCZ.57Q/extr..tion_0000000000000000_0001.0000_5df0a81931a00ba2/ThemeVS2012Light.DLL
----------------------------------------
ExtremeParser
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Gonz%C3%A1lez/AppData/Local/Apps/2.0/LA666H2J.Y66/703WBKCZ.57Q/extr..tion_0000000000000000_0001.0000_5df0a81931a00ba2/ExtremeParser.DLL
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
ColorPicker
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/USERS/GONZ%C3%81LEZ/APPDATA/LOCAL/TEMP/ESPLUGINS/COLORPICKER.DLL
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by rajabilal555** [comment]
I am Also having the Same Issue (using Windows 10 Updated - Latest...) Please Help me Currently I am using Notepad++ but I also like this one if it is more optimized with big scripts... and is more User-friendly to work on, I would really like to migrate to this editor for SAMP(pawno),

 I think it's a Great Project you are working on and I would also like to help you if you would like...

**Comment by JohnyMac** [comment]
Yeah, I'm working on it and will release a fix soon, mostly today.. 

And @rajabilal555, the project is open-source for a reason, everyone is welcome to contribute :)
If your work is good, I might add you as a collaborator. Talk in Gitter if you have more questions.
